services:
  - type: web
    name: memescanner-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://memescannerpro.com,https://www.memescannerpro.com,https://vocal-platypus-2b186a.netlify.app
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        value: ms-prod-2024-secure-key
      - key: POLYGON_RPC
        value: https://polygon-rpc.com
      - key: CONTRACT_ADDRESS
        value: 0xC95e7fCB69666998730c35B26F4B27E3b9Afa692
      - key: OWNER_PRIVATE_KEY
        value: # Dejar vacío - no se necesita para verificar pagos
      - key: USDC_POLYGON
        value: 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174
      - key: USDT_POLYGON
        value: 0xc2132D05D31c914a87C6611C10748AEb04B58e8F
      - key: DAI_POLYGON
        value: 0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063
    healthCheckPath: /api/health